### ISSUE TITLE
Unexpected Crash / Exit...

### ISSUE THREAD

**Issue by aphorise** [mranney/node_redis#744]
I encountered this when trying to use redis-sentinel & realised its occurring after several failed retry attempts during which time I'm also attempting to make as many ```.set```'s & ```.get```'s.

The following: [redis-crash.js](https://github.com/aphorise/redis-sentinel-sim/blob/master/redis-crash.js) - trace is as follows:
```bash
# // node redis-crash.js

hiredis parser not installed.

@========================================@
ERROR: Connecting to REDIS 
@========================================@
ERROR: Connecting to REDIS 
@========================================@
ERROR: Connecting to REDIS 
@========================================@
ERROR w/ GET Error: Redis connection to master_user:56379 failed - getaddrinfo ENOTFOUND
here object
ERROR: Connecting to REDIS 
@========================================@

/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:158
                    throw callback_err;
                          ^
TypeError: Cannot call method 'toString' of undefined
    at Command.callback (/home/mehdi/git/redis-sentinel-sim/redis-crash.js:63:47)
    at RedisClient.flush_and_error (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:155:29)
    at RedisClient.on_error (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:191:10)
    at Socket.<anonymous> (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)

```

The try{}catch{} blocks in this case do not seem to be having any effect. 

Even though read / write approach may be incorrect / illogical it should not be causing a crash right? 

Is this a bug or just pure bad use that can not be patched in node_redis?

**Comment by aphorise** [comment]
I found my issue which was bad toString in my own code. Sorry for the confussion - articulating the issue much a time helps resolve things  :-)
